#!/usr/bin/env sh
DIR="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"

DAT_DIR="$DIR/data"
EXT_DIR="$DIR/extensions"
HOSTS_GEN="$DIR/out/hosts.gen"
HOSTS_OUT="$DIR/out/hosts"

SYSTEM_HOSTS_FILE="/etc/hosts"

MARKER='#--- BEGIN BLOCKED HOSTS ---#'

mkdir -p "$DIR/out"

read_option() {
  read -r answer < /dev/stdin;
  case "$answer" in
    [Yy]|[Yy][Ee][Ss]|"") echo true ;;
    *)                    echo false ;;
  esac
}


printf "Update hosts sources? [Y/n]: "
update_hosts_sources=$(read_option)
if "$update_hosts_sources"; then

  find "$DAT_DIR" "$EXT_DIR" -type f -name 'update.json' | while read -r file; do
    dir="$(dirname "$file")"
    url="$(jq -r '.url' "$file")"
    echo "Updating: $url"
    curl -L "$url" | tr -d '\r' > "$dir/hosts"
  done

fi


printf "Generate hosts file? [Y/n]: "
gen_hosts="$(read_option)"
if "$gen_hosts"; then

  find "$DAT_DIR" "$EXT_DIR" -type f -name 'hosts' -exec cat {} \; | # get all hosts file
    # remove all comments and empty lines
    sed 's/^#.*$\|\s#.*$//' | sed '/^\s*$/d' |
    # remove ipv6 and broadcast addresses
    grep -Ev '^::|^f.*::|^255.' |
    # get domains
    awk '{ print $2 }' |
    # remove local domains
    grep -Ev "^(local|localhost|localhost.localdomain|broadcasthost)$" |
    # remove empty lines
    sed '/^\s*$/d' |
    # sort and remove duplicates
    sort -u |
    # prepend 0.0.0.0
    awk '{ print "0.0.0.0",$1 }' > "$HOSTS_GEN"

  entries=$(wc -l < "$HOSTS_GEN")
  printf "Generated generated file saved to: %s\n" "$HOSTS_GEN"

  if grep -q "$MARKER" "$SYSTEM_HOSTS_FILE"; then
    sed '/'"$MARKER"'/,$d' < "$SYSTEM_HOSTS_FILE" > "$HOSTS_OUT"
  else
    echo "Marker '$MARKER' was not found in $SYSTEM_HOSTS_FILE file!"
    printf "Do you want to generate new hosts file from template? [Y/n]: "
    generate_from_tmpl="$(read_option)"
    if ! "$generate_from_tmpl"; then
        echo "File will not be generated. Place following marker in your $SYSTEM_HOSTS_FILE and re-run script"
        echo "$MARKER"
        echo "Note that all records after marker will be removed"
        exit 1
    fi

    # shellcheck disable=SC2015
    hostname="$([ -f /etc/hostname ] && cat /etc/hostname || hostname)"
    echo "# default hosts generated by shosts

127.0.0.1 localhost
127.0.0.1 local
127.0.1.1 $hostname.localdomain $hostname
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
0.0.0.0 0.0.0.0

" > "$HOSTS_OUT"
  fi

  echo "
$MARKER
#--- Blocked hosts generated by shosts
#--- updated: $(date)
#--- entries: $entries

" >> "$HOSTS_OUT"

  cat "$HOSTS_GEN" >> "$HOSTS_OUT"

  echo "
Inspect $HOSTS_OUT file and apply by executing:

  sudo mv $HOSTS_OUT $SYSTEM_HOSTS_FILE
"

fi

