name: CI
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Uname
        run: |
          echo "uname"

